gencat/participa

app/views/decidim/debates/debates/show.html.erb
docs/HOW_TO_UPGRADE.md

This PR overwrites the detail template of the debate. 
Changed the simple_format method for the decidim_sanitize method in order to render the videos correctly.

overwrites the detail template of the debate

---

Gemfile
Gemfile.lock

upgrade decidim omniauth tag version

---

app/assets/stylesheets/decidim.scss

remove some css styles of titles so that they look just like in production

Fix PIV styles

---

lib/tasks/participa.rake

Change the rake task for when the component is blank instead of nil

fix rake tasks component blank

---

decidim-home/app/cells/decidim/home/content_blocks/feder/show.erb
decidim-home/config/locales/ca.yml
decidim-home/config/locales/es.yml
decidim-home/config/locales/oc.yml

apply link to FEDER contentblock and change text

fix feder content_block text and link

---

db/migrate/20190207080038_add_organization_as_author.decidim_proposals.rb
db/migrate/20190207080041_add_organization_as_author_to_debates.decidim_debates.rb

Due to performance problems and also problems with orphan models some migrations should be refactored.

[FIX] Refactor migrations so that they don't crash during execution.

---

app/assets/stylesheets/decidim.scss
app/assets/stylesheets/general/_navbar.scss
app/assets/stylesheets/general/_processes.scss
app/views/decidim/proposals/proposals/show.html.erb
decidim-home/app/cells/decidim/home/content_blocks/feder/show.erb
decidim-home/config/locales/ca.yml
decidim-home/config/locales/es.yml
decidim-home/config/locales/oc.yml

Fix some styles on menus and links
Fix FEDER size and translations

fix some styles and locales

---

decidim-home/config/locales/ca.yml
decidim-home/config/locales/es.yml
decidim-home/config/locales/oc.yml

Add <br/> on feder block translations

add br on text feder block

---

app/assets/stylesheets/general/_processes.scss

Change color of ul and ol lists inside text
FROM THIS
TO THIS

change color of list inside process

---

app/assets/stylesheets/general/_processes.scss

Change color of ul and ol lists inside text
FROM THIS
TO THIS

Backport change color of list inside process

---

decidim-regulations/app/controllers/decidim/participatory_processes/participatory_processes_controller.rb

Fix processes controller failing metrics

fix metrics failing process_controller

---

app/assets/javascripts/decidim/participa/regulations.js
decidim-regulations/app/controllers/decidim/regulations/regulation_controller.rb
decidim-regulations/app/views/decidim/participatory_processes/participatory_processes/_order_by_processes.html.erb

Changing the default filter of regulations from "All" to "open".

change default filter regulations to open

---

db/migrate/20190424101234_add_missing_indexes.decidim.rb
db/migrate/20190424101235_add_user_group_to_meetings_registrations.decidim_meetings.rb
db/schema.rb

This PR upgrades participa master with last Decidim changes

upgrade with last decidim changes

---

CHANGELOG.md

Add changelog line when installing and activating verifications module for custom actions

add changelog line for verification module

---

CHANGELOG.md

Change Changelog documentation order asc.

fix changelog documentation

---

config/schedule.rb

Rename `open_data` rake task in `config/schedule.rb`
- Related to #70

Rename `open_data` rake task in `config/schedule.rb`

---

Gemfile
Gemfile.lock

Change decidim no newsletter selective tag

add newsletter decidim

---

Gemfile
Gemfile.lock
db/migrate/20190502064440_add_smtp_settings_to_decidim_organizations.decidim.rb
db/schema.rb

upgrade with master and fix selective newsletter query

upgrade with decidim master and fix selective newsletter

---

Gemfile.lock
config/locales/ca_core.yml
config/locales/es_core.yml

add missing newsletter translations

add missing newsletter translations

---

CHANGELOG.md
Gemfile
Gemfile.lock
db/migrate/20190507151030_create_department_admin_areas.decidim_department_admin.rb
db/schema.rb

Add Admin Department Module
- Related to #51

add admin department module

---

config/locales/ca_core.yml
config/locales/es_core.yml

Add `:ca` and `:es` translations
- Related to #50

Add missing newsletters translations

---

Gemfile
Gemfile.lock

In order to have latest fixes form decidim-department_admin gem this PR upgrades to v0.0.3.
- Fixes #?

[CONF] Upgrade to latest version of `decidim-department_admin` module.

---

config/locales/ca_core.yml
config/locales/es_core.yml

Update Newsletters `:ca` `:es` translations
- Related to #89

Update Newsletters :ca :es translations

---

config/application.rb

change time zone

---

decidim-process-extended/app/commands/decidim/participatory_processes/admin/copy_participatory_process.rb
decidim-process-extended/app/commands/decidim/participatory_processes/admin/create_participatory_process.rb
decidim-process-extended/app/commands/decidim/participatory_processes/admin/update_participatory_process.rb
decidim-process-extended/app/decorators/decidim/participatory_process_decorator.rb
decidim-process-extended/app/form/decidim/participatory_processes/admin/participatory_process_form.rb

Fix update decidim_type when updating processes

fix update decidim type when updating processes

---

Gemfile
Gemfile.lock

change decidim branch to master and decidim-department-admin version

change decidim branch to master, and decidim-department-admin version

---

CHANGELOG.md
Gemfile
Gemfile.lock

This PR uprades the decidim department admin module version with the last one.

upgrade decidim department admin

---

Gemfile
Gemfile.lock
db/schema.rb

Change decidim brancg with a backport to prevent crashes

change default branch to prevent crashes

---

Gemfile
Gemfile.lock

change decidim branch to 0.18-stable

change decidim branch to 0.18-stable

---

app/cells/decidim/coauthorships_cell.rb
app/presenters/decidim/proposals/proposal_presenter.rb
docs/HOW_TO_UPGRADE.md

Port to participa the bugfix in https://github.com/decidim/decidim/pull/5383/commits/35b69c9cb80fba850109ca9fce0edb97b5280856 but with mispelling corrected.
- Fixes https://github.com/decidim/decidim/pull/5383/commits/35b69c9cb80fba850109ca9fce0edb97b5280856

[FIX] Use MeetingPresenter when the author is a meeting.

---

app/views/decidim/devise/registrations/new.html.erb
app/views/decidim/devise/sessions/new.html.erb
app/views/decidim/devise/shared/_omniauth_buttons.html.erb
docs/HOW_TO_UPGRADE.md

Change omniauth button position below login form.
Change omniauth button position below registration login.

Change omniauth button position

---

CHANGELOG.md
config/environments/preprod.rb
config/environments/production.rb

Disable custom loggers.
- Related to log-rotate

[CONF] Disable custom loggers.

---

Gemfile
Gemfile.lock

Port changes from #128 in order to deploy into production.
Related to #128

Port changes from #128

---

Gemfile
Gemfile.lock

To allow department admins to upload attachments to Meetings.

Upgrade to department_admin 0.0.10

---

Gemfile
Gemfile.lock

Solve missing permission to :index, :assembly_user_role

Upgrade to decidi-department_admin v0.0.11

---

decidim-home/config/locales/ca.yml

fix literal Uneix-te to Uneix-t'hi

---

decidim-home/config/locales/ca.yml

fix Update literal Uneix-te to Uneix-t'hi

---

decidim-regulations/config/locales/ca.yml
decidim-regulations/config/locales/es.yml
decidim-regulations/config/locales/oc.yml

Treure avis Covid, petició de l'usuaria
- Fixes #?

Delete avis covid

---

Gemfile
Gemfile.lock

As recently has been fixed an admin's profile view error detected in Decidim Department Admin gem, this PR applies new Department Admin release that solves it.

Fix admin's user profile viewing bug

---

Gemfile
Gemfile.lock
db/migrate/20201016080543_create_decidim_term_customizer_translation_sets.decidim_term_customizer.rb
db/migrate/20201016080544_create_decidim_term_customizer_translations.decidim_term_customizer.rb
db/migrate/20201016080545_create_decidim_term_customizer_constraints.decidim_term_customizer.rb
db/schema.rb

Install Decidim Term Customizer module

Install decidim-term_customizer module

---

Gemfile
Gemfile.lock
db/schema.rb

Pull latest from dedidim:decidim/release/0.22-stable to get fix in #6781 .
- Fixes #?

Fix meetings title

---

decidim-regulations/app/views/decidim/regulations/regulation/_promoted_process.html.erb

Highlighted regulations in `/regulations`.
- Fixes #?

Fix highlighted regulations

---

config/initializers/decidim.rb

Disable maps

---

config/initializers/decidim.rb

Throttle has been delegated to load balancer.
- Fixes #?

Remove Rack Attack's throttle

---

Gemfile
Gemfile.lock
bin/server.rb
config/initializers/rack_attack.rb
public/robots.txt

Add custom RackAttack.throttle as gateway is not able to do anything to filter abusive clients.
- Add SemrushBot to robots.txt
- mini script server to listen to requests and print http headers.
- Fixes #?

Custom Rack Attack

---

.github/workflows/linters.yml
app/views/layouts/decidim/mailer.html.erb
lib/tasks/proposals.rake
spec/features/overrides_and_customizations_spec.rb

Enable erblint and comment override test
- Fixes #?

Enable erblint and comment override test

---

Gemfile
Gemfile.lock
lib/tasks/proposals.rake

Admin can not list regulations due to a pending to be updated overriden view in `decidim-department_admin`.
- Fixes #?

Fix admin process list

---

config/initializers/rack_attack.rb
public/robots.txt

Add msn to robots.txt

---

Gemfile.lock

Cherry pick latest commits from https://github.com/decidim/decidim/pull/8143 into Gencat.

Fix order of matrix rows on export answers

---

config/schedule.rb

Add cron for `rake tmp:clear`.
- Fixes #?

Add cron for rake task tmp:clear

---

Gemfile
Gemfile.lock

To get the fix in https://github.com/gencat/decidim-department-admin/pull/43

Update decidim-deptartment_admin to 0.3.2

---

app/assets/stylesheets/general/_footer.scss

Reposition external link in eu logo
- Fixes #?
Desktop:
Mobile

Fix external link in EU logo

---

.github/pull_request_template.md
spec/system/homepage_spec.rb

Participa Gencat doesn't have a test to simply check if the application boots and runs correctly.
This PR adds this test so we have a better test suite for the CI.

Add specs for the homepage

---

Gemfile
Gemfile.lock
db/schema.rb

Get latest features from `decidim-challenges`.

Upgrade decidim-challenges to v0.0.7

---

app/assets/stylesheets/general/_footer.scss

Fix position logo in footer feder
- Fixes #?

Fix position logo feder

---

Gemfile.lock
README.md

This PR gets the fix in https://github.com/CodiTramuntana/decidim/pull/60 to solve many SEO broken links.
- Related to https://github.com/CodiTramuntana/decidim/pull/60

Get Meetings::DiffRenderer fix from Decidim v0.24

---

app/lib/decidim/extensions/locale_switcher_extension.rb
config/environment.rb
spec/controllers/concerns/locale_switcher_spec.rb

Set 'ca' like default locale.
- Fixes #?

Set default locale

---

Gemfile.lock

Pull last commit from department admin to fix department admin filter CSS

Fix Department Admin filter CSS

---

config/initializers/decidim.rb
config/secrets.yml

Enable rack attack configuration via ENV vars

Enable rack attack configuration via ENV vars

---

Gemfile
Gemfile.lock

Get feature in https://github.com/gencat/omniauth-idcat_mobil/pull/14

Get latest omniauth-idcat_mobil

---

Gemfile.lock
config/initializers/webpacker.rb
spec/features/overrides_and_customizations_spec.rb

Get publish survey alert feature from v0.26 stable backport.
- Related to https://github.com/CodiTramuntana/decidim/pull/95

Get publish survey alert feature

---

decidim-type/config/routes.rb
lib/middlewares/redirect_middleware.rb
spec/system/redirect_middleware_spec.rb

- Add Redirect for "Assemblea Clima inscripcions"
- Add corresponding test

Redirect asamblea clima inscriptions

---

Gemfile.lock

Not send email when user is not registered in surveys

Not send email when user is not registered in surveys

---

config/initializers/rack_attack.rb

Add blocklist_ip to RackAttack with an environment var.

Add blocklist_ip to RackAttack

---

config/initializers/rack_attack.rb

Blocklist each ip in a separate `blocklist_ip` declaration.
- Fixes https://github.com/gencat/participa/pull/460

Fix Blocklist each ip separately

---

docs/HOW_TO_UPGRADE.md
public/robots.txt

Disallow access to:
- profiles
- comments
- searches

Add certain routes to robots.txt

---

Gemfile.lock

Update Decidim with last version to fix create and accept amendments

Update Decidim with last version
