gencat/participa

- Gemfile
- Gemfile.lock
Do not depend directly upon the git repo but instead use the published versions in rubygems.
> [CONF] Use stable versions for idcat_mobil related gems.

- decidim-regulations/app/controllers/decidim/participatory_processes/participatory_processes_controller.rb
Re-add participatory processos with customizations to not show process groups in the process index page.
> fix participatory processes index view, not show processes groups

- decidim-regulations/app/controllers/decidim/participatory_processes/participatory_processes_controller.rb
- decidim-regulations/app/queries/decidim/participatory_processes/filtered_participatory_processes.rb
Re-add participatory processos with customizations to not show process groups in the process index page.
> Backport fix participatory processes index show

- config/schedule.rb
Rename `open_data` rake task in `config/schedule.rb`
- Related to #70
> [Backport] Rename `open_data` rake task in `config/schedule.rb`

- CHANGELOG.md
- app/assets/stylesheets/decidim.scss
- Hide assemblies type filter
- Related to #82
> Hide assemblies type filter

- CHANGELOG.md
- Gemfile
- Gemfile.lock
Prevent department_admin of being displayed as a component.
- Fixes #?
- [-] Add documentation regarding the feature 
- [-] Add/modify seeds
- [-] Add tests
> Prevent department_admin of being displayed as a component.

- config/application.rb
In order to correctly override Decidim's artifacts, we must make sure that Decidim is loaded before decidim-department_admin gem.
- Related to #51
> [CONFIG] Ensure department_admin gem is loaded after decidim-core.

- CHANGELOG.md
- Gemfile
- Gemfile.lock
In order to  get the feature "admin list has an area column" this PR upgrades `decidim-department_admin` module.
> Upgrade decidim-department_admin module to latest

- config/application.rb
Revert application default time zone to UTC
> Revert application default time zone to UTC

- CHANGELOG.md
- decidim-process-extended/app/commands/decidim/participatory_processes/admin/copy_participatory_process.rb
This PR fix when copying process/regulations
> fix when copying process/regulations

- config/environments/production.rb
In order to reduce log volume in the production environment, log level should be setted to the standard Rails log level for production, which is :info.
- Fixes #?
- [-] Add `CHANGELOG` entry
- [-] Add documentation regarding the feature 
- [-] Add/modify seeds
- [-] Add tests
> [CONF] Change production log level to :info.

- CHANGELOG.md
- config/locales/ca_core.yml
- config/locales/es_core.yml
- config/locales/oc_core.yml
- decidim-process-extended/app/views/decidim/participatory_processes/admin/participatory_processes/_form.html.erb
- decidim-process-extended/config/locales/ca.yml
- decidim-process-extended/config/locales/es.yml
- docs/HOW_TO_UPGRADE.md
- Resort participatory process cost field.
- Rename translation for participatory process custom fields.
- Clarify registration nickname help. (remove '@sobrenom')
- Related to:
> I18n fix/clarify registration nickname help

- CHANGELOG.md
- config/application.rb
There is a 1 hour delay in the application respect our timezone region. In this PR, we set Europe/Madrid timezone to default.
- Fixes #?
> [FIX] Set default timezone to Europe/Madrid

- CHANGELOG.md
- config/application.rb
There is a 1 hour delay in the application respect our timezone region. In this PR, we set Madrid timezone to default.
- Fixes #?
> [Backport] Set default timezone to Europe/Madrid (#124)

- Gemfile
- Gemfile.lock
To allow department admins to manage assembly user roles.
> Upgrade to department_admin 0.0.9

- Gemfile
- Gemfile.lock
Apply the patch in https://github.com/gencat/decidim-department-admin/pull/27 that is compatible with current Decidim version in participa, decidim v0.18.
The compatible version can be found in latest version of the branch `0.0.11-stable` in department_admin: https://github.com/gencat/decidim-department-admin/tree/0.0.11-stable
> Upgrade decidim-department_admin to latest

- app/forms/decidim/debates/admin/debate_form.rb
- docs/HOW_TO_UPGRADE.md
When editing a existing debate with Start / End dates, and only wanted to change one of the dates, the form validator threw an error because the other unchanged date field wasn't in wrong format, so form builder couldn't assign it to form.
This causes that this field was unassigned to form, so when debate's form validation field checked it, threw and error.
> Fix debate edit dates issue

- docker-compose.yml
The postgres image needs a super user password
```
pg_1     | Error: Database is uninitialized and superuser password is not specified.
pg_1     |        You must specify POSTGRES_PASSWORD to a non-empty value for the
pg_1     |        superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
pg_1     |
pg_1     |        You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
pg_1     |        connections without a password. This is *not* recommended.
pg_1     |
pg_1     |        See PostgreSQL documentation about "trust":
pg_1     |        https://www.postgresql.org/docs/current/auth-trust.html
gencat_participa_pg_1 exited with code 1
```
> Fix postgres container configuration

- app/decorators/decidim/meetings/admin/meeting_form_decorator.rb
- docs/HOW_TO_UPGRADE.md
When editing a existing meeting with Start / End dates, and only wanted to change one of the dates, the form validator threw an error because the other unchanged date field wasn't in wrong format, so form builder couldn't assign it to form.
This causes that this field was unassigned to form, so when meeting's form validation field checked it, threw and error.
https://github.com/gencat/participa/pull/165
- Fixes #?
> fix meeting dates

- db/schema.rb
The schema.rb file has an incorrect migration version
> Fix migration version on schema.rb

- app/assets/stylesheets/general/_header.scss
This fixes the top left Home's logo that now is cut.
- Fixes #164 
**Before**
**After**
> Fix wrong Gencat logo in top left Home

- Gemfile.lock
Upgrade to latest 0.22 to get fix for highlighted participatory processes titles.
> Fix highlighted participatory processes title

- app/assets/stylesheets/general/_fixes.scss
When the screen is small in the user's nickname field on the registration form, the label appears in the wrong position.
- Fixes #?
The nickname is not showed correctly
The nickname now is fixed
> Fix style on user registration nickname field when display is small

- app/assets/stylesheets/general/_header.scss
The search input form on header is dark by default. Setting it with a white background and fix the lens icon color will improve the user experience.
- Fixes #?
before:
after:
> Override style for header input search form

- app/decorators/decidim/participatory_processes/permissions_decorator.rb
- app/decorators/decidim/participatory_space_context_decorator.rb
- docs/HOW_TO_UPGRADE.md
When in a Private Participatory Process, all invited private users don't have visibility to public's Participatory Process page.
This PR checks and solves this issue to allow them to see that public's page.
Before:
After:
> Fix permissions's lack to private participatory space to invited private users

- docs/HOW_TO_UPGRADE.md
- lib/decidim/has_private_users.rb
Private users can not access private ParticipatoryProcesses.
This PR complements https://github.com/gencat/participa/pull/194
- Related to https://github.com/gencat/participa/pull/194
> Fix, temporarily, permission to answer private space questionnaire

- Gemfile.lock
The ajax call that retrieves the data for the metrics in participatory processes does not filter by space id due to a bug in decidim/decidim: https://github.com/decidim/decidim/pull/6971 
This PR updates Decidim to latest 0.22 with the bugfix
> Upgrade to fix metrics in show participatory proces

- Gemfile
- Gemfile.lock
Upgrade `decidim-department_admin` gem to v0.0.16 to get:
- A user can only belong to one single department.
- When a department_admin is promoted to admin, she looses the role and the department.
> Upgrade decidim-department_admin to v0.0.16

- Gemfile.lock
Get latest commit from gencat:decidim to get the fix for the newsletter participants count.
> Get the fix for the newsletter participants count

- decidim-top_comments/app/views/decidim/proposals/proposals/_most_voted_comment.html.erb
Decidim v0.23 refactors Proposal.body making it multilanguage.
This PR makes adapts top_comments to be compatible to both Decidim 0.22 and 0.23 and higher.
> Add coditional to transition from Decidim v0.22 to v0.23 and up

- Gemfile
- Gemfile.lock
- decidim-top_comments/app/controllers/concerns/decidim/proposals/positive_negative_comments.rb
- decidim-top_comments/app/views/decidim/proposals/proposals/_most_voted_comment.html.erb
- decidim-top_comments/app/views/decidim/proposals/proposals/_most_voted_comments.html.erb
- decidim-top_comments/config/locales/ca.yml
- decidim-top_comments/config/locales/en.yml
- decidim-top_comments/config/locales/es.yml
- decidim-top_comments/config/locales/oc.yml
- decidim-top_comments/spec/system/most_voted_comments_spec.rb
This PR adds counters and percentages to Top Comments block.
For each kind of comments, in favor and against, it renders the count and the percentage.
This PR also improves,  in performance terms, the algorithm to select the most voted comment of each kind.
> Add counters and percentages to Top Comments

- config/application.rb
We're in Rails 5.2 and there's no need to use rails 5.1 defaults.
> Use Rails 5.2 defaults

- Gemfile
- Gemfile.lock
Upgrade to decidim `release/0.24-stable` in CodiTramuntana's fork.
Ports:
- Fully copy question's display_conditions from template #8200
- Fix create questionnaire from template when no template is selected #8185
- Fix ordering of question matrix_rows in templates #8186
> Port fixes to questionnaires and templates

- Gemfile
- Gemfile.lock
Upgrade version of gem decidim-department_admin to 3.3 to get fix: Department admin on "millora visualització rols" when the user was in table department_admin_areas and has no role "department_admin" it shows like if it was a department_admin
- Related to https://github.com/gencat/decidim-department-admin/commit/5d0922ca2448dc7753ab952520faea1457321572
- Fixes https://github.com/gencat/decidim-department-admin/pull/44
> upgrade decidim-department_areas to version 3.3

- decidim-process-extended/app/serializers/decidim/participatory_processes/participatory_process_serializer.rb
- decidim-process-extended/spec/serializers/decidim/participatory_processes/participatory_process_serializer_spec.rb
The open data exporter to Socrata, when serializing the participatory process, it was using `process_group.name` instead of `process_group.title`. This attribute was changed by the migration `RenameNameColumnToTitleInDecidimParticipatoryProcessGroups` in v0.24.
> Fix serialization of participatory_space name

- Gemfile
- Gemfile.lock
When debugging the problem with meetings DiffRenderer we've found that there's an incompatibility between decidim-department_admin and participa.gencat.cat since version `v0.2.0` but it manifested recently.
It's been solved in: https://github.com/gencat/decidim-department-admin/pull/46
- Related to https://github.com/gencat/decidim-department-admin/pull/46
> Upgrade to decidim-department_admin v0.3.4

- Gemfile
- Gemfile.lock
The repository URL of the `department_admin` gem has changed. This PR updates the URL in this project's `Gemfile`.
- Related to https://github.com/gencat/decidim-module-department_admin/pull/49
> Change department_admin's URL

- db/migrate/20211129174157_remove_decidim_custom_categorization_tables_after_migrate_to_decidim_standards.rb
- db/schema.rb
Remove Decidim legacy categorization tables after migrating to Decidim standards.
This DB cleaning should have been done long time ago. See `DecidimDepartment, DecidimTheme, DecidimType` in  the `CHANGELOG`.
> Remove legacy tables

- Gemfile.lock
- app/assets/javascripts/decidim/participa/regulations.js
- config/initializers/future_europe_redirect.rb
- lib/middlewares/redirect_middleware.rb
- spec/features/overrides_and_customizations_spec.rb
- spec/models/organizations_spec.rb
- spec/system/future_europe_spec.rb
The application should redirect from path `/futur-europa` to the regular url `/processes/FuturEuropa`
> Redirect for "futur-europa" url

- Gemfile
- Gemfile.lock
Because of an upgrade of `omniauth` library a clash of method names appeared between this library and `omiauth-idcat_mobil`. This PR solves this problem by getting the fix implemented in `omiauth-idcat_mobil`.
> Upgrade idcat_mobil libs

- Gemfile
- Gemfile.lock
Yet another bug has been found in the idcat mòbil integration. Because of an incorrect log trace, the session state was being removed before it was checked by oauth2. This PR solves this problem by getting the fix implemented in omiauth-idcat_mobil.
> Upgrade decidim-idcat_mobil

- decidim-regulations/app/services/decidim/regulations/regulation_search.rb
```
PG::InvalidParameterValue: ERROR:  time zone "Madrid" not recognized
: SELECT "decidim_participatory_processes".* FROM "decidim_participatory_processes" WHERE "decidim_participatory_processes"."decidim_participatory_process_group_id" = $1 AND "decidim_participatory_processes"."decidim_organization_id" = $2 AND "decidim_participatory_processes"."published_at" IS NOT NULL AND "decidim_participatory_processes"."decidim_participatory_process_group_id" = $3 ORDER BY ABS(start_date - (CURRENT_DATE at time zone 'Madrid')::date)
```
The TimeZone has been fixed because when performing the "All" filter in regulations it gave an previous error.
- Fixes #?
> Fix TimeZone in sql query

- Gemfile
- Gemfile.lock
Take latest version of `decidim-idcat_mobil` to participa.
> Upgrade decidim-idcat_mobil to v0.1.0

- decidim-home/app/overrides/layouts/decidim/_main_footer/pre_footer.html.erb.deface
Fix error with a new hash.
```
D, [2022-01-31T11:40:38.183222 #10798] DEBUG -- : [be124875-7e09-49c0-a1eb-a8c4f422ae23] Deface: 1 overrides found for 'layouts/decidim/_main_footer'
D, [2022-01-31T11:40:38.184622 #10798] DEBUG -- : [be124875-7e09-49c0-a1eb-a8c4f422ae23] Deface: 'pre_footer' matched 1 times with '.main-footer'
E, [2022-01-31T11:40:38.185181 #10798] ERROR -- : [be124875-7e09-49c0-a1eb-a8c4f422ae23] Deface: [ERROR] The original source for 'pre_footer' has changed, this override should be reviewed to ensure it's still valid.
```
- Fixes #?
> Update Deface hash in pre_footer

- Gemfile.lock
- decidim-process-extended/app/overrides/layouts/admin/participatory_process.rb
- decidim-process-extended/app/views/decidim/participatory_processes/admin/participatory_processes/_proposal_component_alert.html.erb
- decidim-process-extended/config/locales/ca.yml
- decidim-process-extended/config/locales/es.yml
- spec/factories.rb
- spec/system/admin/participatory_processes/admin_manages_participatory_processes_spec.rb
When participatory process is created and the group is "Normativa", then it shows an alert in order to create and publish  the proposal component.
- Fixes #?
> Alert in Participatory Processes for proposal component activation

- decidim-process-extended/app/views/decidim/participatory_processes/admin/participatory_processes/_proposal_component_alert.html.erb
Inside a component, the variable group is nil.
Fixes #282
> Fix publish alert when Group is nil inside a Component (proposal, blog..)

- Gemfile
- Gemfile.lock
Use released gem versions instead of depending on volatile branches.
> Use released gem versions where possible

- package-lock.json
When installing JS packages in the servers npm changes the `package-lock.json` file.
This PR updates it is not changed when deployed.
> Avoid differences between repository and deployed JS packages

- Gemfile
- Gemfile.lock
- config/secrets.yml
In order to be sure that `IdCat mobil` initializer is using the correct variables this PR adds all `idcat_mobil` env vars to secrets. This way when not defined in the organization default variables are correctly readed.
- Related to https://3.basecamp.com/4186608/buckets/11242950/todos/5800549107
> Add all idcat_mobil env vars to secrets

- spec/features/overrides_and_customizations_spec.rb
Check that in future upgrades of Decidim we do not lost the new features have just backported last week about improvements in surveys.
> Update overrides and customizations tests

- decidim-process-extended/app/views/decidim/participatory_processes/participatory_processes/show.html.erb
In the last update processes extended was not synchronized with changes from Decidim 0.26
> Fix the override of the show of a participatory process

- config/environments/preprod.rb
Set the log level to :info for the `preprod` environment because log files increase too much unnecessarily.
> Raise log level to :info for :preprod env

- decidim-process-extended/app/serializers/decidim/participatory_processes/participatory_process_serializer.rb
This PR changes the behavior of the process_type field send to Socrata.
Now all processes are of type virtual. If they have also meetings they will be both, thus of type "ambdos".
> All processes are always, at least, virtual

- app/packs/stylesheets/decidim/decidim_application.scss
In lists, number and text are overlapping
Now, there are not space between number and text in lists.
> Fix space between number and text in li elements in Quill editor

- config/initializers/decidim.rb
Extract session duration configuration into an `EXPIRE_SESSION_AFTER` environment variable.
> Extract session duration configuration into an env variable

- config/initializers/decidim.rb
As `EXPIRE_SESSION_AFTER` is retrieved as a String from the ENV, it does not support `.hours`. Thus, it must first be parsed into an integer before converting to `.hours`.
- Fixes #461
> Fix parsing of EXPIRE_SESSION_AFTER env var

- config/initializers/decidim.rb
When EXPIRE_SESSION_AFTER was not set, zero was being taken as default.
This PR fixes this by fixing the logic of the `||` and allowing half hours by parsing to float instead of integer.
- Fixes https://github.com/gencat/participa/pull/461
> Fix empty EXPIRE_SESSION_AFTER results in no session at all

- config/initializers/rack_attack.rb
Bad crawlers use farms to crawl the site without being banned. As these farms use the same IP range, we're banning bad behaved IP ranges.
> Configure RackAttack for IP ranges

- decidim-home/app/overrides/layouts/decidim/_main_footer/pre_footer.html.erb.deface
- decidim-top_comments/app/overrides/decidim/debates/debates/show.html.erb.deface
Deface overrides errors:
`
[1;32mDeface:[0m 'pre_footer' matched 1 times with '.main-footer'[1;32mDeface: [ERROR][0m The original source for 'pre_footer' has changed, this override should be reviewed to ensure it's still valid.
`
`E, [2024-11-08T10:56:05.385633 #1190517] ERROR -- : [703b7857-ff29-41f6-9d63-c7736c8ddfad] ESC[1;32mDeface: [ERROR]ESC[0m The original source for 'show' has changed, this override should be reviewed to ensure it's still valid.`
> Update deface originals

- Gemfile
- Gemfile.lock
Fixes in members pickers and department admin related with upgrade to 0.27
Related PRs:
https://github.com/gencat/decidim-module-department_admin/pull/68
https://github.com/gencat/decidim-verifications-members_picker/pull/9
> Fixes in members pickers and department admin related with upgrade to 0.27

- config/secrets.yml
During the task of upgrading to Decidim 0.28, the `idcat_mobil` omniauth entry in `config/secrets.yml` was incorrectly indented, preventing the platform to use its configuration from environment variables. This PR fixes that indentation.
- Related to #497
> Fix idcat_mobil entry indentation in secrets.yml

- decidim-regulations/app/cells/decidim/regulations/content_blocks/highlighted_regulations_cell.rb
- decidim-regulations/app/cells/decidim/regulations/content_blocks/highlighted_regulations_settings_form/show.erb
- decidim-regulations/lib/decidim/regulations/engine.rb
Modify value for highlighted regulations on home config admin panel to allow select multiple of 3 values on selector.
Also, the default value has to be 6 instead of 4 or 8.
Fix the value limit for elements to show on home highlighted regulations to get the home admin panel configuration.
- Related to https://3.basecamp.com/4186608/buckets/11242950/todos/8194747486#__recording_8252489039
- Fixes https://3.basecamp.com/4186608/buckets/11242950/todos/8194747486#__recording_8252489039
> Modify values for highlighted_regulations on home config admin panel

- .github/workflows/test.yml
There's an error on github actions test with upload-artifact version.
Review Dependant bot's PR
> Fix upgrade upload-artifact library to avoid deprecation error on test workflow

- decidim-regulations/README.md
- decidim-regulations/app/cells/decidim/regulations/content_blocks/highlighted_regulations_cell.rb
Add a documentation of how the regulations are ordered in highlighted content block
- Related to https://3.basecamp.com/4186608/buckets/11242950/todos/8194747486
> Add ordering regulations documentation on readme

- .github/workflows/linters.yml
- .github/workflows/test-process_extended.yml
- .github/workflows/test-recaptcha.yml
- .github/workflows/test-top_comments.yml
- .github/workflows/test.yml
- .github/workflows/validate_migrations.yml
- CHANGELOG.md
- docs/HOW_TO_UPGRADE.md
It's already time to use current git standard for default branch, so we move from `master` to `main`.
> Move default branch from master to main

- lib/participa_gencat/softcatala_translator.rb
- spec/lib/participa_gencat/softcatala_translator_spec.rb
When a translation fails, it is now set as `nil` but  this causes problems in other parts of the system that expect them to be, at least, an empty string.
Now if the translation client returns nil, the attribute is set to an empty string.
> Do not set empty String instead of nil when translation fail

- decidim-home/app/overrides/layouts/decidim/footer/_main/feder_footer.html.erb.deface
Updated the `alt` attribute of the FEDER image in the footer override to reflect the actual text in the image:  
"Unió Europea. Fons Europeu de Desenvolupament Regional".
- Fixes #?
> Fix alt text for FEDER image in footer override

- config/initializers/decidim.rb
This PR updates the content_security_policies_extra in config/initializers/decidim.rb to include the necessary domains for Google Tag Manager and Piwik to function correctly.
- Fixes #?
> Update CSP settings to allow Google Tag Manager and Piwik domains
